spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: kevin
    password: 1234
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security: DEBUG